name: dispatch_event
on:
  repository_dispatch:
    types: [imagepushed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Check variables
      env:
        PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload.data) }}
      run: |
          echo "::set-env name=repo_name::${{ github.event.client_payload.data.target.repository }}"
          echo "::set-env name=repo_version::${{ github.event.client_payload.data.target.tag }}"
          echo "::set-env name=image_name::${{ github.event.client_payload.data.target.repository }}:${{ github.event.client_payload.data.target.tag }}"
          
    - name: Set Context for Azure Kubernetes Cluster using azure/aks-set-context@v1 action
      uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: k8cluster3
        resource-group: PythonSdk
